export enum OrderStatus {
  CREATED = 'CREATED',
  AWAITING_TRANSFER = 'AWAITING_TRANSFER',
  FUNDS_RECEIVED = 'FUNDS_RECEIVED',
  PROCESSING = 'PROCESSING',
  SETTLED = 'SETTLED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}
